"""
Report generator — fpdf2 (pure Python, no system deps)
Professional snagging report with summary and tables
"""
from datetime import datetime
from typing import List, Dict, Any
from fpdf import FPDF


class SnagReport(FPDF):
    def __init__(self, project, inspector):
        super().__init__()
        self.project = project
        self.inspector = inspector
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(255, 107, 53)
        self.cell(0, 8, "SNAGGING REPORT", ln=True)
        self.set_font("Helvetica", "", 11)
        self.set_text_color(51, 51, 51)
        self.cell(0, 6, self.project.get("name", ""), ln=True)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, f"Client: {self.project.get('client', '-')}", ln=True)
        self.cell(0, 5, f"Date: {datetime.now().strftime('%d %b %Y')}  |  Inspector: {self.inspector}  |  Ref: SF-{self.project.get('id', '')[:8].upper()}", ln=True)
        self.set_draw_color(255, 107, 53)
        self.set_line_width(0.8)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(170, 170, 170)
        self.cell(0, 10, f"Generated by SnagFlow  |  Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(255, 107, 53)
        self.cell(0, 8, title.upper(), ln=True)
        self.set_draw_color(230, 230, 230)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def summary_box(self, label, value, color=(51, 51, 51)):
        x = self.get_x()
        y = self.get_y()
        self.set_fill_color(245, 245, 245)
        self.rect(x, y, 43, 22, "F")
        self.set_xy(x, y + 3)
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(*color)
        self.cell(43, 10, str(value), align="C", ln=False)
        self.set_xy(x, y + 14)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(130, 130, 130)
        self.cell(43, 5, label.upper(), align="C", ln=False)
        self.set_xy(x + 46, y)

    def snag_table(self, snags, show_priority=True):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(245, 245, 245)
        self.set_text_color(80, 80, 80)
        col_widths = [10, 75, 45, 25, 30] if show_priority else [10, 85, 55, 30]
        headers = ["#", "Description", "Location", "Priority", "Date"] if show_priority else ["#", "Description", "Location", "Date"]
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, border=1, fill=True, align="L")
        self.ln()
        self.set_font("Helvetica", "", 8)
        self.set_text_color(50, 50, 50)
        for idx, snag in enumerate(snags):
            row_data = [str(idx + 1)]
            note = snag.get("note", "")
            if len(note) > 60:
                note = note[:57] + "..."
            row_data.append(note)
            row_data.append(snag.get("location", "-") or "-")
            if show_priority:
                row_data.append(snag.get("priority", "medium").upper())
            row_data.append(snag.get("created_at", "")[:10])
            for i, val in enumerate(row_data):
                self.cell(col_widths[i], 6, val, border=1, align="L")
            self.ln()


def generate_report_pdf(project, snags, inspector_email):
    open_snags = [s for s in snags if s["status"] == "open"]
    closed_snags = [s for s in snags if s["status"] == "closed"]
    high_priority = [s for s in open_snags if s.get("priority") == "high"]
    pdf = SnagReport(project, inspector_email)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.section_title("Summary")
    pdf.ln(2)
    y_start = pdf.get_y()
    pdf.summary_box("Total Snags", len(snags))
    pdf.summary_box("Open", len(open_snags), color=(239, 68, 68))
    pdf.summary_box("Closed", len(closed_snags), color=(34, 197, 94))
    pdf.summary_box("High Priority", len(high_priority), color=(245, 158, 11))
    pdf.set_y(y_start + 28)
    if open_snags:
        pdf.section_title(f"Open Snags ({len(open_snags)})")
        pdf.snag_table(open_snags, show_priority=True)
        pdf.ln(4)
    if closed_snags:
        pdf.section_title(f"Closed Snags ({len(closed_snags)})")
        pdf.snag_table(closed_snags, show_priority=False)
    return pdf.output()