"""
Reports router — generate professional PDF inspection reports.

Two entry points:
  GET  /api/reports/{project_id}           → download PDF
  POST /api/reports/{project_id}/email     → email PDF to recipients

Both go through `_build_project_report_pdf()` which fetches project/visit/snags,
downloads photos, resolves the company plan, and returns the generated bytes
plus metadata. The email endpoint then chooses attach-vs-link based on size.
"""
import re
import uuid
import httpx
from io import BytesIO
from typing import Optional
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, EmailStr

from app.services.auth_dep import get_current_user
from app.services.supabase_client import supabase_admin
from app.services.report_generator import generate_report_pdf
from app.services.plan_enforcement import get_company_plan, require_feature
from app.services.emails import send_report_email
from app.config import settings

router = APIRouter()

# Size above which we upload to Storage + send a signed URL instead of attaching.
# 10 MB raw becomes ~13 MB Base64 — well within Resend's 40 MB cap AND within
# Gmail/Outlook's 25 MB recipient-side limit. Reports bigger than this get
# emailed as a link instead.
EMAIL_ATTACHMENT_THRESHOLD_MB = 10
EMAIL_ATTACHMENT_THRESHOLD_BYTES = EMAIL_ATTACHMENT_THRESHOLD_MB * 1024 * 1024

# How long the signed download link is valid for link-mode emails.
REPORT_LINK_EXPIRY_SECONDS = 7 * 24 * 3600   # 7 days
REPORT_LINK_EXPIRY_DAYS = 7

# Bucket where PDFs are uploaded for link-mode email delivery.
# (Private bucket — signed URLs only.)
REPORT_EXPORTS_BUCKET = "report-exports"

# Max recipients per email-report request (safety / anti-abuse)
MAX_RECIPIENTS_PER_EMAIL = 10


# ─── Photo + helper fetches ─────────────────────────────────────

async def _download_photo(url: str) -> bytes | None:
    """Download photo bytes from a signed Supabase URL."""
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.get(url)
            if resp.status_code == 200:
                return resp.content
    except Exception:
        pass
    return None


async def _get_company_settings(user_id: str) -> dict:
    """
    Fetch everything the PDF renderer needs about the user's company in
    ONE query: logo bytes, name, and all report_* settings.

    Returns a dict with keys:
      - logo_bytes: Optional[bytes]
      - name: str
      - brand_colour: str (#RRGGBB)
      - footer_text: Optional[str]
      - include_rectification: bool
      - include_cover_page: bool
      - photos_per_page: int
      - title_align: str ('center' | 'left')

    Safe against missing company: returns sensible defaults so the PDF
    still renders if, for some reason, the user has no company yet.
    """
    defaults = {
        "logo_bytes": None,
        "name": "",
        "brand_colour": "#F97316",
        "footer_text": None,
        "include_rectification": False,
        "include_cover_page": True,
        "photos_per_page": 2,
        "title_align": "center",
    }

    cols = (
        "logo_path, name, "
        "report_brand_colour, report_footer_text, "
        "report_include_rectification, report_include_cover_page, "
        "report_photos_per_page, report_title_align"
    )

    try:
        # Owned company first
        company = (
            supabase_admin.table("companies")
            .select(cols)
            .eq("owner_id", user_id)
            .limit(1)
            .execute()
        )
        row = company.data[0] if company.data else None

        # Fall back to membership
        if not row:
            mem = (
                supabase_admin.table("company_members")
                .select(f"companies({cols})")
                .eq("user_id", user_id)
                .limit(1)
                .execute()
            )
            if mem.data and mem.data[0].get("companies"):
                row = mem.data[0]["companies"]

        if not row:
            return defaults

        # Resolve logo bytes (signed URL → download) if a logo_path exists
        logo_bytes = None
        logo_path = row.get("logo_path")
        if logo_path:
            try:
                url_res = supabase_admin.storage.from_("company-logos").create_signed_url(logo_path, 300)
                url = url_res.get("signedURL") or url_res.get("signedUrl")
                if url:
                    logo_bytes = await _download_photo(url)
            except Exception:
                pass  # Non-fatal — render without logo.

        # Validate title_align — DB CHECK should enforce this, but be defensive
        # in case the migration hasn't run yet (column missing → .get returns None).
        title_align_raw = (row.get("report_title_align") or "center").strip().lower()
        title_align = title_align_raw if title_align_raw in ("center", "left") else "center"

        return {
            "logo_bytes": logo_bytes,
            "name": row.get("name") or "",
            "brand_colour": row.get("report_brand_colour") or defaults["brand_colour"],
            "footer_text": row.get("report_footer_text"),
            "include_rectification": bool(row.get("report_include_rectification", False)),
            "include_cover_page": row.get("report_include_cover_page", True) is not False,
            "photos_per_page": int(row.get("report_photos_per_page") or 2),
            "title_align": title_align,
        }
    except Exception:
        return defaults


async def _get_company_logo(user_id: str) -> bytes | None:
    """Fetch the company logo bytes for branding."""
    try:
        company = (
            supabase_admin.table("companies")
            .select("logo_path")
            .eq("owner_id", user_id)
            .limit(1)
            .execute()
        )
        if not company.data:
            mem = (
                supabase_admin.table("company_members")
                .select("companies(logo_path)")
                .eq("user_id", user_id)
                .limit(1)
                .execute()
            )
            if mem.data and mem.data[0].get("companies"):
                logo_path = mem.data[0]["companies"].get("logo_path")
            else:
                return None
        else:
            logo_path = company.data[0].get("logo_path")

        if not logo_path:
            return None

        url_res = supabase_admin.storage.from_("company-logos").create_signed_url(logo_path, 300)
        url = url_res.get("signedURL") or url_res.get("signedUrl")
        if url:
            return await _download_photo(url)
    except Exception:
        pass
    return None


async def _get_company_name(user_id: str) -> str:
    """Get company name for the user."""
    try:
        company = (
            supabase_admin.table("companies")
            .select("name")
            .eq("owner_id", user_id)
            .limit(1)
            .execute()
        )
        if company.data:
            return company.data[0].get("name", "")
        mem = (
            supabase_admin.table("company_members")
            .select("companies(name)")
            .eq("user_id", user_id)
            .limit(1)
            .execute()
        )
        if mem.data and mem.data[0].get("companies"):
            return mem.data[0]["companies"].get("name", "")
    except Exception:
        pass
    return ""


async def _get_inspector_name(user_id: str) -> str:
    """Get inspector's full name from profiles table."""
    try:
        profile = (
            supabase_admin.table("profiles")
            .select("first_name, last_name")
            .eq("id", user_id)
            .single()
            .execute()
        )
        if profile.data:
            first = profile.data.get("first_name", "")
            last = profile.data.get("last_name", "")
            full = f"{first} {last}".strip()
            if full:
                return full
    except Exception:
        pass
    return ""


# ─── Shared PDF builder ─────────────────────────────────────────

class ReportBuildResult:
    """Return value of _build_project_report_pdf."""
    def __init__(
        self,
        pdf_bytes: bytes,
        project_name: str,
        visit_no: str,
        summary: dict,
        inspector_name: str,
    ):
        self.pdf_bytes = pdf_bytes
        self.project_name = project_name
        self.visit_no = visit_no
        self.summary = summary
        self.inspector_name = inspector_name


async def _build_project_report_pdf(
    *,
    project_id: str,
    user: dict,
    visit_id: str = "",
    include_closed: bool = True,
    include_photos: bool = True,
    weather: str = "",
    visit_no: str = "",
) -> ReportBuildResult:
    """
    Shared logic for both the download and email endpoints.

    Fetches project (with owner check), visit, snags, photos, company info,
    and plan, then generates the PDF. Raises HTTPException for any data
    problem — callers can let it propagate or catch it.
    """
    # Project (also enforces ownership)
    proj = (
        supabase_admin.table("projects")
        .select("*")
        .eq("id", project_id)
        .eq("user_id", user["id"])
        .single()
        .execute()
    )
    if not proj.data:
        raise HTTPException(status_code=404, detail="Project not found")

    # Visit
    visit_data = None
    if visit_id:
        visit_res = (
            supabase_admin.table("site_visits")
            .select("*")
            .eq("id", visit_id)
            .single()
            .execute()
        )
        if visit_res.data:
            visit_data = visit_res.data
            if not weather:
                weather = visit_data.get("weather", "")
            if not visit_no:
                visit_no = str(visit_data.get("visit_no", ""))

    # Resolve display number for the PDF body. visit_ref is an optional
    # user override (e.g. "MIL-V01", "2026/04/13"). When blank, we fall
    # back to the integer visit_no. The filename helper uses visit_no
    # directly regardless — filenames stay stable even if the user
    # changes their display scheme mid-project.
    visit_display = ""
    if visit_data:
        raw_ref = (visit_data.get("visit_ref") or "").strip()
        if raw_ref:
            visit_display = raw_ref
    if not visit_display:
        visit_display = visit_no  # falls back to the integer

    # Snags
    query = (
        supabase_admin.table("snags")
        .select("*")
        .eq("project_id", project_id)
        .order("created_at", desc=False)
    )
    if visit_id:
        query = query.eq("visit_id", visit_id)
    if not include_closed:
        query = query.eq("status", "open")
    snags_res = query.execute()

    # Photos
    snags: list[dict] = []
    photo_data: dict[str, list[bytes]] = {}
    for s in snags_res.data:
        photo_url = None
        if include_photos:
            photos_for_snag: list[bytes] = []
            for path_key in ["photo_path", "photo_path_2", "photo_path_3", "photo_path_4"]:
                path = s.get(path_key)
                if path:
                    try:
                        url_res = supabase_admin.storage.from_("snag-photos").create_signed_url(path, 300)
                        url = url_res.get("signedURL") or url_res.get("signedUrl")
                        if not photo_url and path_key == "photo_path":
                            photo_url = url
                        if url:
                            img_bytes = await _download_photo(url)
                            if img_bytes:
                                photos_for_snag.append(img_bytes)
                    except Exception:
                        pass

            rect_path = s.get("rectification_photo_path")
            if rect_path:
                try:
                    url_res = supabase_admin.storage.from_("snag-photos").create_signed_url(rect_path, 300)
                    url = url_res.get("signedURL") or url_res.get("signedUrl")
                    if url:
                        img_bytes = await _download_photo(url)
                        if img_bytes:
                            photos_for_snag.append(img_bytes)
                except Exception:
                    pass

            if photos_for_snag:
                photo_data[s["id"]] = photos_for_snag

        snags.append({**s, "photo_url": photo_url})

    # Company settings — logo, name, branding, report toggles (Phase 1)
    settings = await _get_company_settings(user["id"])
    logo_bytes = settings["logo_bytes"]
    company_name = settings["name"]

    # Inspector / plan
    profile_name = await _get_inspector_name(user["id"])
    inspector = profile_name or (visit_data.get("inspector", "") if visit_data else "") or user.get("email", "")
    plan_slug, _company_id = await get_company_plan(user["id"])

    # Build the PDF
    pdf_bytes = generate_report_pdf(
        project=proj.data,
        snags=snags,
        inspector_email=inspector,
        logo_bytes=logo_bytes,
        photo_data=photo_data,
        weather=weather,
        visit_no=visit_no,
        visit_display=visit_display,
        attendees=visit_data.get("attendees", "") if visit_data else "",
        access_notes=visit_data.get("access_notes", "") if visit_data else "",
        company_name=company_name,
        checker=visit_data.get("checker", "") if visit_data else "",
        reviewer=visit_data.get("reviewer", "") if visit_data else "",
        approver=visit_data.get("approver", "") if visit_data else "",
        closing_notes=visit_data.get("closing_notes", "") if visit_data else "",
        user_email=user.get("email", ""),
        plan=plan_slug,
        # Phase 1 — per-company report settings
        brand_colour=settings["brand_colour"],
        footer_text=settings["footer_text"],
        include_rectification=settings["include_rectification"],
        # Phase 2 — layout mode + cover alignment
        photos_per_page=settings["photos_per_page"],
        title_align=settings["title_align"],
    )

    # Summary (used by email body; GET endpoint doesn't strictly need it but
    # cheap to compute)
    open_snags = [s for s in snags if s.get("status") == "open"]
    closed_snags = [s for s in snags if s.get("status") == "closed"]
    high_priority = [s for s in open_snags if s.get("priority") == "high"]
    summary = {
        "total": len(snags),
        "open": len(open_snags),
        "closed": len(closed_snags),
        "high_priority": len(high_priority),
    }

    return ReportBuildResult(
        pdf_bytes=pdf_bytes,
        project_name=proj.data.get("name", "Project"),
        visit_no=visit_no or "1",
        summary=summary,
        inspector_name=profile_name or "",
    )


def _slug(s: str, max_len: int = 40) -> str:
    """URL-safe lowercase slug for filenames."""
    s = re.sub(r"[^A-Za-z0-9._-]+", "-", (s or "").strip())
    s = s.strip("-").lower()[:max_len]
    return s or "report"


def _project_code(project_name: str) -> str:
    """
    Derive a short project code from the project name.
    Takes the first whitespace-separated token, strips everything that isn't
    a letter/digit/dash/underscore, and uppercases. Capped at 12 chars.

    Examples:
      'MIL06 — Basement Retrofit'     → 'MIL06'
      'MIL06-West Tower'              → 'MIL06-WEST'   (split on space, keep dashes)
      'Project Alpha'                 → 'PROJECT'
      '  '                            → 'REPORT'       (fallback)
    """
    if not project_name:
        return "REPORT"
    tokens = project_name.split()
    if not tokens:
        return "REPORT"
    first = tokens[0]
    cleaned = re.sub(r"[^A-Za-z0-9_-]", "", first).upper()
    return cleaned[:12] or "REPORT"


def _report_filename(project_name: str, report_no_input: str) -> str:
    """
    Build the download filename for a report.

    Rules (see memory note on task #9):
      - Empty / missing → {CODE}_SVR_{NNN}.pdf  (auto-increment, zero-padded to 3)
      - Purely numeric  → {CODE}_SVR_{NNN}.pdf  (still zero-pads)
      - Anything else   → {CODE}_{user_input}.pdf  (sanitized)

    The auto-increment source is the visit_no the caller already resolved
    (from the site_visit row or from the URL query). That's a per-project
    counter managed by site_visits so it naturally auto-increments.
    """
    code = _project_code(project_name)
    raw = (report_no_input or "").strip()

    if not raw:
        # Empty → default to SVR_001. Shouldn't happen often in practice
        # because the caller passes visit_no which defaults to "1".
        return f"{code}_SVR_001.pdf"

    if raw.isdigit():
        # Numeric → padded SVR format
        return f"{code}_SVR_{int(raw):03d}.pdf"

    # Custom string → use it verbatim (sanitized for filesystem safety)
    sanitized = re.sub(r"[^A-Za-z0-9_-]", "_", raw)
    sanitized = sanitized.strip("_")[:40]
    if not sanitized:
        # Input was all noise characters — treat as empty
        return f"{code}_SVR_001.pdf"
    return f"{code}_{sanitized}.pdf"


# ─── GET endpoint (download) ────────────────────────────────────

@router.get("/{project_id}")
async def get_report(
    project_id: str,
    visit_id: str = Query("", description="Site visit ID (optional, generates for specific visit)"),
    include_closed: bool = True,
    include_photos: bool = True,
    weather: str = Query("", description="Weather conditions"),
    visit_no: str = Query("", description="Visit number"),
    user: dict = Depends(get_current_user),
):
    """Generate and return a PDF inspection report as a download."""
    result = await _build_project_report_pdf(
        project_id=project_id,
        user=user,
        visit_id=visit_id,
        include_closed=include_closed,
        include_photos=include_photos,
        weather=weather,
        visit_no=visit_no,
    )

    filename = _report_filename(result.project_name, result.visit_no)
    pdf_bytes = result.pdf_bytes

    # Return the PDF as a file download. Notes on headers:
    #   - attachment disposition forces browsers to download instead of
    #     rendering inline. This is what desktop browsers honour; iOS is
    #     inconsistent here (often opens in-browser anyway), but setting it
    #     doesn't hurt and helps Android Chrome.
    #   - filename uses both `filename=` (legacy ASCII) and `filename*=UTF-8`
    #     (RFC 5987) so non-ASCII project names render correctly on all
    #     browsers. The legacy value is sanitized ASCII-safe by the
    #     `_report_filename` helper upstream.
    #   - Content-Length lets the browser show a download progress bar
    #     (otherwise mobile users see "Generating..." indefinitely even
    #     after the bytes are in flight).
    #   - Access-Control-Expose-Headers lets client JS read the filename
    #     from the response if it wants to (we don't today, but harmless).
    from urllib.parse import quote
    filename_ascii = filename.encode("ascii", "ignore").decode("ascii") or "report.pdf"
    content_disposition = (
        f'attachment; filename="{filename_ascii}"; '
        f"filename*=UTF-8''{quote(filename)}"
    )

    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": content_disposition,
            "Content-Length": str(len(pdf_bytes)),
            "Access-Control-Expose-Headers": "Content-Disposition, Content-Length",
            "Cache-Control": "no-store",
        },
    )


# ─── POST endpoint (email) ──────────────────────────────────────

class EmailReportRequest(BaseModel):
    to: list[EmailStr]
    visit_id: Optional[str] = ""
    weather: Optional[str] = ""
    visit_no: Optional[str] = ""
    include_closed: Optional[bool] = True
    message: Optional[str] = None  # custom note from sender


@router.post("/{project_id}/email")
async def email_report(
    project_id: str,
    body: EmailReportRequest,
    user: dict = Depends(get_current_user),
):
    """
    Generate the PDF and email it to `body.to`.

    - Gated behind the `email_reports` plan feature (Team+).
    - PDFs <10 MB are attached directly; larger reports are uploaded to
      Supabase Storage and sent as a time-limited signed-URL link.
    """
    # ── Plan gate ──────────────────────────────────────────────
    plan_slug, _company_id = await get_company_plan(user["id"])
    require_feature(
        plan_slug,
        "email_reports",
        "Emailing reports requires the Team plan or higher. Upgrade to unlock.",
    )

    # ── Validate recipients ────────────────────────────────────
    recipients = [str(r).strip() for r in (body.to or []) if str(r).strip()]
    if not recipients:
        raise HTTPException(status_code=400, detail="At least one recipient is required")
    if len(recipients) > MAX_RECIPIENTS_PER_EMAIL:
        raise HTTPException(
            status_code=400,
            detail=f"Too many recipients (max {MAX_RECIPIENTS_PER_EMAIL} per send)",
        )
    if body.message and len(body.message) > 2000:
        raise HTTPException(status_code=400, detail="Message too long (max 2000 chars)")

    # ── Build the PDF ──────────────────────────────────────────
    result = await _build_project_report_pdf(
        project_id=project_id,
        user=user,
        visit_id=body.visit_id or "",
        include_closed=bool(body.include_closed),
        include_photos=True,
        weather=body.weather or "",
        visit_no=body.visit_no or "",
    )

    pdf_size = len(result.pdf_bytes)
    pdf_filename = _report_filename(result.project_name, result.visit_no)

    # ── Decide: attach vs upload-and-link ──────────────────────
    if pdf_size <= EMAIL_ATTACHMENT_THRESHOLD_BYTES:
        # Attachment mode
        ok = await send_report_email(
            to=recipients,
            project_name=result.project_name,
            visit_no=result.visit_no,
            sender_name=result.inspector_name,
            sender_email=user.get("email", ""),
            summary=result.summary,
            pdf_bytes=result.pdf_bytes,
            pdf_filename=pdf_filename,
            custom_message=body.message,
        )
        mode = "attachment"
    else:
        # Link mode — upload to Storage, create signed URL
        storage_path = _upload_report_to_storage(
            user_id=user["id"],
            project_id=project_id,
            filename=pdf_filename,
            pdf_bytes=result.pdf_bytes,
        )
        if not storage_path:
            raise HTTPException(
                status_code=500,
                detail=(
                    f"Report is too large to attach ({pdf_size / 1024 / 1024:.1f} MB) "
                    f"and could not be uploaded to storage. Please try again, or "
                    f"use 'Download PDF' and share the file yourself."
                ),
            )

        signed = supabase_admin.storage.from_(REPORT_EXPORTS_BUCKET).create_signed_url(
            storage_path, REPORT_LINK_EXPIRY_SECONDS
        )
        download_url = signed.get("signedURL") or signed.get("signedUrl")
        if not download_url:
            raise HTTPException(
                status_code=500,
                detail="Could not generate a download link for the report. Please try again.",
            )

        ok = await send_report_email(
            to=recipients,
            project_name=result.project_name,
            visit_no=result.visit_no,
            sender_name=result.inspector_name,
            sender_email=user.get("email", ""),
            summary=result.summary,
            download_url=download_url,
            download_size_mb=pdf_size / 1024 / 1024,
            download_expires_days=REPORT_LINK_EXPIRY_DAYS,
            custom_message=body.message,
        )
        mode = "link"

    if not ok:
        raise HTTPException(
            status_code=502,
            detail="Failed to send the report email. Please try again.",
        )

    return {
        "status": "sent",
        "mode": mode,
        "recipients": recipients,
        "size_mb": round(pdf_size / 1024 / 1024, 2),
    }


def _upload_report_to_storage(
    *,
    user_id: str,
    project_id: str,
    filename: str,
    pdf_bytes: bytes,
) -> Optional[str]:
    """
    Upload a PDF to the report-exports bucket.

    Returns the storage path on success, None on failure. Uses a UUID prefix
    so repeated sends don't overwrite each other and so the URL is hard to
    guess even if someone has the bucket name.
    """
    token = uuid.uuid4().hex
    path = f"{user_id}/{project_id}/{token}-{filename}"
    try:
        supabase_admin.storage.from_(REPORT_EXPORTS_BUCKET).upload(
            path,
            pdf_bytes,
            {"content-type": "application/pdf"},
        )
        return path
    except Exception:
        return None


# ─── Existing preview endpoint (unchanged) ──────────────────────

@router.get("/{project_id}/preview")
async def preview_report(
    project_id: str,
    visit_id: str = Query("", description="Site visit ID"),
    user: dict = Depends(get_current_user),
):
    """Return report data as JSON for frontend preview."""
    proj = (
        supabase_admin.table("projects")
        .select("*")
        .eq("id", project_id)
        .eq("user_id", user["id"])
        .single()
        .execute()
    )
    if not proj.data:
        raise HTTPException(status_code=404, detail="Project not found")

    query = (
        supabase_admin.table("snags")
        .select("*")
        .eq("project_id", project_id)
        .order("created_at", desc=False)
    )
    if visit_id:
        query = query.eq("visit_id", visit_id)

    snags_res = query.execute()

    open_snags = [s for s in snags_res.data if s["status"] == "open"]
    closed_snags = [s for s in snags_res.data if s["status"] == "closed"]
    high_priority = [s for s in open_snags if s["priority"] == "high"]

    return {
        "project": proj.data,
        "summary": {
            "total": len(snags_res.data),
            "open": len(open_snags),
            "closed": len(closed_snags),
            "high_priority": len(high_priority),
        },
        "snags": snags_res.data,
    }
